# Generated by Django 5.0.7 on 2024-08-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farm', '0002_rename_crop_farmprofile_cropname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('N', models.FloatField(null=True)),
                ('P', models.FloatField(null=True)),
                ('K', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('ph', models.FloatField(null=True)),
                ('rainfall', models.FloatField(null=True)),
                ('farmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_environment', to='Farm.farmprofile')),
            ],
            options={
                'db_table': 'EnvironmentLog',
            },
        ),
    ]
