# Generated by Django 5.0.7 on 2024-08-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropSelection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEnvironment',
            fields=[
                ('cropName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('N', models.FloatField(null=True)),
                ('P', models.FloatField(null=True)),
                ('K', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('ph', models.FloatField(null=True)),
                ('rainfall', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'DefaultEnvironment',
            },
        ),
    ]
