# Generated by Django 5.0.7 on 2024-08-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('status', models.FloatField()),
                ('farmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_devices', to='Farm.farmprofile')),
            ],
            options={
                'db_table': 'Device',
            },
        ),
    ]
