# Generated by Django 5.0.7 on 2024-08-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Manage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="isAuto",
            field=models.BooleanField(default=False),
        ),
    ]
