# Generated by Django 5.0.7 on 2024-08-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiseaseLog",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("farmName", models.CharField(max_length=100)),
                ("disease", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "DiseaseLog",
            },
        ),
    ]
