# Generated by Django 5.0.7 on 2024-08-11 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='Farm.farmprofile')),
            ],
            options={
                'db_table': 'DiseaseLog',
            },
        ),
    ]
