# Generated by Django 5.0.7 on 2024-08-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CropDisease', '0002_diseaselog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaselog',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
