# Generated by Django 5.0.7 on 2024-08-13 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('farmID', models.AutoField(primary_key=True, serialize=False)),
                ('farmName', models.CharField(max_length=100)),
                ('cropName', models.CharField(max_length=100)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FarmProfile',
            },
        ),
    ]
