# Generated by Django 5.0.7 on 2024-07-29 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmProfile",
            fields=[
                (
                    "farmID",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("crop", models.CharField(max_length=100)),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to="Users.user",
                    ),
                ),
            ],
            options={
                "db_table": "FarmProfile",
                "unique_together": {("farmID", "userID")},
            },
        ),
    ]
