# Generated by Django 5.0.7 on 2024-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropPricePredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crop Price Prediction',
                'verbose_name_plural': 'Crop Price Predictions',
                'db_table': 'CropPricePredict',
                'unique_together': {('crop', 'date')},
            },
        ),
    ]
